property_providers:
  - add_default:
      properties:
        preferred_driver: mitamae

driver_options:
  mitamae:
    mitamae_path: /home/k0kubun/bin/mitamae
    #mitamae_options: ['-l', 'debug']
    mitamae_prepare_script: |
      mkdir -p /home/k0kubun/bin &&
      wget -O /home/k0kubun/bin/mitamae https://github.com/itamae-kitchen/mitamae/releases/download/v1.7.5/mitamae-x86_64-linux &&
      echo "920eaf5a7a154ee66b0c6fe54e6313177666729aafbbb41d675436d7b99f1165  /home/k0kubun/bin/mitamae" | shasum -a 256 -c &&
      chmod +x /home/k0kubun/bin/mitamae
